### ISSUE TITLE
NoClassDefFoundError with Groovy 2.4

### ISSUE THREAD

**Issue by masatonagai** [gperfutils/gprof#7]
```
java.lang.NoClassDefFoundError: org/codehaus/groovy/reflection/ClassInfo$ClassInfoSet
	at groovyx.gprof.Profiler.getLoadedClasses(Profiler.java:202)
	at groovyx.gprof.Profiler.proxyMetaClasses(Profiler.java:166)
	at groovyx.gprof.Profiler.start(Profiler.java:139)
	at groovyx.gprof.Profiler.run(Profiler.java:95)
	at groovyx.gprof.Profiler.run(Profiler.java:62)
	at groovyx.gprof.Profiler$run.call(Unknown Source)
```

**Comment by spmallette** [comment]
:+1:

**Comment by dkuppitz** [comment]
:+1:

**Comment by rmagen** [comment]
+1

**Comment by mhfrantz** [comment]
:+1:

**Comment by PommeVerte** [comment]
Seconding this. Would be nice to see a fix

**Comment by masatonagai** [comment]
Just fixed.  I will release the next version that includes this fix soon ;)

**Comment by spmallette** [comment]
works nicely - thanks for the fix.

**Comment by nadeemajl** [comment]
This worked thanks!
